### ISSUE TITLE
Game not recognizing language.

### ISSUE THREAD

**Issue by ekureina** [christopho/zelda_roth_se#80]
I'm trying to add Spanish support to this quest. I have the half finished files in the es/ directory under languages, but the quest does not add Español as a valid language option in the language selection screen.

**Comment by christopho** [comment]
Did you add Spanish language using the quest editor?
The quest editor is now the preferred way to edit dialogs, there is a nice gui since 1.4. It tells you what is already translated and what is not.

If you are doing it by hand, then you should add a language line to project_db.dat, maybe this is what is missing.

Anyway, I hope you are aware that there already exists a Spanish translation of the original game:
http://www.zeldaroth.fr/es/files/ROTH/Linux/ZeldaROTH_ES-src-linux.zip
Importing it should only take a couple of hours, by copy-pasting each dialog at the right place.
We can discuss this on IRC.

**Comment by ekureina** [comment]
Ok, thanks, I was doing it by hand and forgot to add it to project_db.dat.
